common/models/Image.php
<?php

namespace common\models;

use common\models\helper\ImageHelper;
use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%image}}".
 *
 * @property integer $id
 * @property string $filename
 * @property integer $item_id
 * @property string $model_name
 * @property string $title
 * @property integer $sort_index
 * @property integer $folder
 */
class Image extends ActiveRecord
{

    public static function tableName()
    {
        return '{{%image}}';
    }

    public function rules()
    {
        return [
            [['filename', 'item_id', 'model_name'], 'required'],
            [['item_id', 'sort_index'], 'integer'],
            [['filename', 'model_name', 'title', 'folder'], 'string', 'max' => 255],
        ];
    }


    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'filename' => 'Filename',
            'folder' => 'Folder',
            'item_id' => 'Item ID',
            'model_name' => 'Model Name',
            'title' => 'Title',
            'sort_index' => 'Sort Index',
        ];
    }


    public function behaviors()
    {
        return [
            'sort' => [
                'class' => 'himiklab\sortablegrid\SortableGridBehavior',
                'sortableAttribute' => 'sort_index'
            ],
        ];

    }


    public function afterDelete()
    {
        parent::afterDelete(); //
        if ($this->checkFileExists()){
            unlink($this->filePath);
        }
    }

    public static function create($filename, $model_name, $item_id, $folder = false){
        $image = new self;
        $image->filename = $filename;
        $image->model_name = $model_name;
        $image->folder = $folder;
        $image->item_id = $item_id;
        $image->save();
    }


    public function getImage()
    {
        return ImageHelper::getImage($this->filename, $this->folder);
    }

    public function getWmImage()
    {
        return ImageHelper::getWmImage($this->filename, $this->folder);
    }

    public function getImagePath()
    {
        return ImageHelper::getImagePath($this->filename, $this->folder);
    }

    public function getWmImagePath()
    {
        return ImageHelper::getWmImagePath($this->filename, $this->folder);
    }


    public function getFileLink(){
        if ($this->checkFileExists()) {
            $file = ($this->folder) ? $this->folder.'/'.$this->filename : $this->filename;
            return Yii::getAlias('@imagesWebroot').'/' . $file;
        } else {
            return null;
        }
    }


    public function getFilePath(){
        if ($this->checkFileExists()) {
            $file = ($this->folder) ? $this->folder.'/'.$this->filename : $this->filename;
            return Yii::getAlias('@images').'/' . $file;
        } else {
            return null;
        }
    }


    public function checkFileExists(){
        if ($this->filename) {
            $file = ($this->folder) ? $this->folder.'/'.$this->filename : $this->filename;
            $filePath = Yii::getAlias('@images/') . ($file);
            if (file_exists($filePath)) {
                return true;
            } else {
                return false;
            }
        }
    }
}

frontend/controllers/ServicesController.php
<?php
namespace frontend\controllers;

use frontend\models\Content;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class ServicesController extends Controller
{

    public function actionIndex()
    {
        $category = null;

        $query = Content::find()->published();
        $query->withSection(Content::SECTION_SERVICE);
        $query->orderBy('sort_index DESC');

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 12,
            ],
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'category' => $category,
        ]);
    }


    public function actionView($slug){

        $model = $this->findModel($slug);
        $model->updateCounters(['views' => 1]);

        $models = Content::find()->published()->withSection(Content::SECTION_SERVICE)->orderBy('sort_index DESC')->limit(10)->all();

        return $this->render('view', [
            'model' => $model,
            'models' => $models
        ]);

    }


    protected function findModel($slug)
    {
        if (($model = Content::find()->where(['slug' => $slug])->withSection(Content::SECTION_SERVICE)->one()) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(t('Page not found'));
        }
    }
}

frontend/views/services/_item.php
<?php
?>

<div class="services-item card hoverable h-100">
    <a href="<?= url(['/services/view', 'slug' => $model->slug]) ?>" class="d-block card-body">
        <img src="<?= thumb($model->imagePath, 400, 300, true) ?>" alt="" class="mb-3">
        <span class="d-block"> <?= $model->title ?> </span>
    </a>
</div>







frontend/views/services/index.php
<?php
use yii\widgets\ListView;

$this->title = t('Services').' | '. siteName();

$this->params['breadcrumbs'][] = t('Services');

$this->registerMetaTag(['name'=> 'keywords', 'content' => 'Проект электроосвещения, Аудит и оптимизация существующего проекта, Подбор светотехнического оборудование, Светотехническое проектирование, Светотехнический расчет, Светодизайн']);
$this->registerMetaTag(['name' => 'description', 'content' => 'Наша компания предоставляет клиентам широкий спектр услуг: от разработки плана освещения и его реализации до аудита уже существующего проекта.']);

?>
<div class="container">
    <h1 class="page-title"><?= t('Services') ?></h1>
	
	<div>
		<?= txt('services_desc') ?>
	</div>
	<br/>
	
    <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => '_item',
        'options' => [
            'class' => 'services-list row'
        ],
        'itemOptions' => [
            'class' => 'col-lg-3 mb-3 ',
        ],
        'layout' => "{items}\n{pager}",
    ]) ?>
</div>

frontend/views/services/view.php
<?php
use common\models\Settings;
use frontend\models\Content;

/** @var Content $model */
$this->title = $model->getSeoTitle();

$this->params['breadcrumbs'][] = ['label' => t('Services'), 'url' => ['/news']];
$this->params['breadcrumbs'][] = $model->title;

$this->registerMetaTag(['name'=> 'keywords', 'content' => $model->meta_keywords]);
$this->registerMetaTag(['name'=> 'description', 'content' => $model->meta_description]);

?>


<div class="container">
    <div class="content-view">
        <div class="row">
            <div class="col-lg-3 order-lg-1 order-2">
                <?php if ($models) { ?>
                    <div class="list-group">
                        <?php foreach ($models as $item){ ?>
                            <a href="<?= url(['/services/view', 'slug' => $item->slug]) ?>" class="list-group-item list-group-item-action">
                                <?= h($item->title) ?>
                            </a>
                        <?php  } ?>
                    </div>
                <?php } ?>
            </div>
            <div class="col-lg-9 order-lg-2 order-1 mb-3">
                <h1 class="page-title"><?= $model->title?></h1>
                <?php if ($model->photo) { ?>
                    <div class="text-center mt-2 mb-2">
                        <img src="<?= $model->image ?>" alt="<?= $model->title ?>" />
                    </div>
                <?php } ?>

                <?= $model->desc?>
            </div>

        </div>
    </div>
</div>