frontend/controllers/VacancyController.php
<?php
namespace frontend\controllers;

use frontend\models\Content;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class VacancyController extends Controller
{

    public function actionIndex()
    {
        $category = null;

        $query = Content::find()->published();
        $query->withSection(Content::SECTION_VACANCY);
        $query->orderBy('sort_index DESC');

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'category' => $category,
        ]);
    }


    public function actionView($slug){

        $model = $this->findModel($slug);
        $model->updateCounters(['views' => 1]);

        return $this->render('view', [
            'model' => $model
        ]);

    }


    protected function findModel($slug)
    {
        if (($model = Content::find()->where(['slug' => $slug])->withSection(Content::SECTION_VACANCY)->one()) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(t('Page not found'));
        }
    }
}

frontend/views/vacancy/_item.php
<?php
use yii\helpers\Html;
?>
<div class="mb-3 shadow-sm">
    <div class="vacancy-item p-4">
        <div class="row align-items-center">
            <div class="col-lg-2 mb-2">
                <?= Yii::$app->formatter->asDate($model->created_at) ?>
            </div>
            <div class="col-lg-3 mb-3">
                <strong>
                    <?= h($model->title) ?>
                </strong>
            </div>
            <div class="col-lg-5 mb-4">
                <?= substr($model->intro, 0 , 200) ?>
            </div>
            <div class="col-lg-2 text-lg-center">
                <?= Html::a(t('Readmore'), ['/vacancy/view', 'slug' => $model->slug], ['class' => 'btn btn-outline-main']) ?>
            </div>
        </div>
    </div>
</div>








frontend/views/vacancy/index.php
<?php
use yii\widgets\ListView;
use common\models\Settings;

$this->title = Settings::getValue('site_name');

$this->params['breadcrumbs'][] = t('Vacancies');
$this->registerMetaTag(['name' => 'description', 'content' => 'Сейчас наша команда в поиске молодых и перспективных специалистов. Смотрите актуальные вакансии на сайте.']);

?>
<div class="container">
    <h1 class="page-title"><?= t('Career') ?></h1>
    
    <div class="text-center mb-4">
        <img src="/img/team.jpg" alt="" class="shadow">
    </div>

	<div>
		<?= txt('vacancy_desc') ?>
	</div>
	<br/>
	
    <div class="mb-3 shadow-sm d-none d-lg-block">
        <div class="vacancy-item p-4 font-weight-bold">
            <div class="row align-items-center">
                <div class="col-lg-2">
                    <?= t('Date') ?>
                </div>
                <div class="col-lg-3">
                    <?= t('Position') ?>
                </div>
                <div class="col-lg-5">
                    <?= t('Additionally') ?>
                </div>
                <div class="col-lg-2 text-center">
                </div>
            </div>
        </div>
    </div>
    <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => '_item',
        'layout' => "{items}\n{pager}",
    ]) ?>
</div>

<style>
	.feedback {
		display: none;
	}
</style>

frontend/views/vacancy/view.php
<?php
use common\models\Settings;

$this->title = $model->title.' | '.siteName();

$this->params['breadcrumbs'][] = ['label' => t('Vacancies'), 'url' => ['/vacancy']];
$this->params['breadcrumbs'][] = $model->title;

$this->registerMetaTag(['name'=> 'keywords', 'content' => $model->meta_keywords]);
$this->registerMetaTag(['name'=> 'description', 'content' => $model->meta_description]);

?>

<div class="container">
    <div class="content-view">
        <h1><?= $model->title?></h1>
        <br>
        <?= $model->desc?>
    </div>
</div>

<?= \frontend\widgets\feedback\ResumeFormWidget::widget(); ?>