common/models/Image.php
<?php

namespace common\models;

use common\models\helper\ImageHelper;
use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%image}}".
 *
 * @property integer $id
 * @property string $filename
 * @property integer $item_id
 * @property string $model_name
 * @property string $title
 * @property integer $sort_index
 * @property integer $folder
 */
class Image extends ActiveRecord
{

    public static function tableName()
    {
        return '{{%image}}';
    }

    public function rules()
    {
        return [
            [['filename', 'item_id', 'model_name'], 'required'],
            [['item_id', 'sort_index'], 'integer'],
            [['filename', 'model_name', 'title', 'folder'], 'string', 'max' => 255],
        ];
    }


    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'filename' => 'Filename',
            'folder' => 'Folder',
            'item_id' => 'Item ID',
            'model_name' => 'Model Name',
            'title' => 'Title',
            'sort_index' => 'Sort Index',
        ];
    }


    public function behaviors()
    {
        return [
            'sort' => [
                'class' => 'himiklab\sortablegrid\SortableGridBehavior',
                'sortableAttribute' => 'sort_index'
            ],
        ];

    }


    public function afterDelete()
    {
        parent::afterDelete(); //
        if ($this->checkFileExists()){
            unlink($this->filePath);
        }
    }

    public static function create($filename, $model_name, $item_id, $folder = false){
        $image = new self;
        $image->filename = $filename;
        $image->model_name = $model_name;
        $image->folder = $folder;
        $image->item_id = $item_id;
        $image->save();
    }


    public function getImage()
    {
        return ImageHelper::getImage($this->filename, $this->folder);
    }

    public function getWmImage()
    {
        return ImageHelper::getWmImage($this->filename, $this->folder);
    }

    public function getImagePath()
    {
        return ImageHelper::getImagePath($this->filename, $this->folder);
    }

    public function getWmImagePath()
    {
        return ImageHelper::getWmImagePath($this->filename, $this->folder);
    }


    public function getFileLink(){
        if ($this->checkFileExists()) {
            $file = ($this->folder) ? $this->folder.'/'.$this->filename : $this->filename;
            return Yii::getAlias('@imagesWebroot').'/' . $file;
        } else {
            return null;
        }
    }


    public function getFilePath(){
        if ($this->checkFileExists()) {
            $file = ($this->folder) ? $this->folder.'/'.$this->filename : $this->filename;
            return Yii::getAlias('@images').'/' . $file;
        } else {
            return null;
        }
    }


    public function checkFileExists(){
        if ($this->filename) {
            $file = ($this->folder) ? $this->folder.'/'.$this->filename : $this->filename;
            $filePath = Yii::getAlias('@images/') . ($file);
            if (file_exists($filePath)) {
                return true;
            } else {
                return false;
            }
        }
    }
}

frontend/models/Portfolio.php
<?php

namespace frontend\models;


class Portfolio extends Content
{
    const SECTION = 'portfolio';

    public function getProducts()
    {
        return $this->hasMany(Product::className(), ['id' => 'product_id'])
            ->viaTable('{{%shop_product_portfolio}}', ['portfolio_id' => 'id'])
            ->andWhere(['status_id' => 1]);
    }
}

frontend/controllers/PortfolioController.php
<?php

namespace frontend\controllers;

use common\modules\content\models\ModuleConstant;
use frontend\models\ContentCategory;
use frontend\models\Portfolio;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class PortfolioController extends Controller
{
    public function actionIndex($slug = false, $year = false){

        if (!$slug){

            $models = ContentCategory::find()->withSection(Portfolio::SECTION)->published()->orderBy('sort_index')->all();
            return $this->render('index', [
                'models' => $models
            ]);

        } else {

            $category = $this->findCategory($slug);

            $query = Portfolio::find()->alias('t1')
                ->leftJoin('{{%content_category}} as cat', 'cat.content_id=t1.id')
                ->andWhere(['t1.status_id' => ModuleConstant::ACTIVE])
                ->andWhere(['t1.section' => Portfolio::SECTION])
                ->andWhere(['cat.category_id' => $category->id]);

            if (!$year) {
                $year = date('Y');
            }

            if ($year != 'all') {
                $query->andWhere(['t1.year' => $year]);
            }

            $dataProvider = new ActiveDataProvider([
                'query' => $query,
                'pagination' => [
                    'pageSize' => 20,
                ],
            ]);

            return $this->render('category', [
                'year' => $year,
                'category' => $category,
                'dataProvider' => $dataProvider
            ]);
        }

    }


    public function actionView($slug){

        $model = $this->findModel($slug);
        $model->updateCounters(['views' => 1]);

        $relatedProducts = $model->products;


        return $this->render('view', [
            'model' => $model,
            'relatedProducts' => $relatedProducts,
        ]);

    }


    protected function findCategory($slug)
    {
        if (($model = ContentCategory::find()->withSlug($slug)->withSection(Portfolio::SECTION)->published()->one()) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(\Yii::t('app', 'Page not found'));
        }
    }


    protected function findModel($slug)
    {
        if (($model = Portfolio::find()->withSlug($slug)->withSection(Portfolio::SECTION)->published()->one()) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(\Yii::t('app', 'Page not found'));
        }
    }
}

frontend/views/portfolio/_item.php
<?php
?>
<a href="<?= url(['/portfolio/view', 'slug' => $model->slug]) ?>" class="portfolio-item d-block h-100">
    <img src="<?= thumb($model->imagePath, 600, 400, true) ?>" alt="" class="hoverable mb-2">
    <span class="d-block mb-3"> <?= $model->title ?> </span>
</a>






frontend/views/portfolio/category.php
<?php

use frontend\widgets\portfolio\PortfolioSorterWidget;
use yii\widgets\ListView;

if ($year && $year != 'all') {
    $this->title = t('Portfolio {year}', 'app', ['year' => $year]).$category->title;

} else {
    $this->title = t('Portfolio').' | '.$category->title;
}

$this->params['breadcrumbs'][] = ['label' => t('Portfolio'), 'url' => ['/portfolio/index']];
$this->params['breadcrumbs'][] = $category->title;

$this->registerMetaTag(['name' => 'description', 'content' => $category->metaDescription]);

?>
<div class="container">

    <div class="row align-items-center pt-2 pb-2">
        <div class="col-lg-9 col-12">
            <h1 class="page-title"><?= $category->title ?></h1>
        </div>
        <div class="col-lg-3 col-12">
            <?= PortfolioSorterWidget::widget(['category' => $category, 'defaultYear' => date("Y")]) ?>
        </div>
    </div>
	
	<p><?= $category->desc ?></p>
    <br>

    <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => '_item',
        'options' => [
            'class' => 'portfolio-list row'
        ],
        'itemOptions' => [
            'class' => 'col-lg-3 mb-3',
        ],
        'layout' => "{items}\n{pager}",
    ]) ?>
</div>

frontend/views/portfolio/index.php
<?php

$this->title .= t('Portfolio').' || '.siteName();

$this->params['breadcrumbs'][] = t('Portfolio');

$this->registerMetaTag(['name'=> 'keywords', 'content' => '']);
$this->registerMetaTag(['name'=> 'description', 'content' => 'Ознакомьтесь с нашими проектами в сферах концепции визуализации, фасадное освещение, наружное освещение и внутреннее освещение.']);

?>

<div class="container">
    <h1 class="page-title"><?= t('Portfolio') ?></h1>
    <div class="row">
        <?php if ($models){ ?>
            <?php foreach ($models as $model){ ?>
                <div class="col-lg-3">
                    <a href="<?= url(['/portfolio/index', 'slug' => $model->slug]) ?>" class="hoverable d-block p-2">
                        <img src="<?= thumb($model->imagePath, 400, 400) ?>" alt="" class="mb-2">
                        <span class="d-block mb-2 p-2 text-center">
                            <?= $model->title ?>
                        </span>
                    </a>
                </div>
            <?php } ?>
        <?php } ?>
    </div>
</div>


frontend/views/portfolio/view.php
<?php
use frontend\models\Content;

/** @var Content $model */
$this->title = $model->getSeoTitle();

$this->params['breadcrumbs'][] = ['label' => t('Portfolio'), 'url' => ['/portfolio/index']];
if ($model->category) {
    $this->params['breadcrumbs'][] = ['label' => $model->category->title, 'url' => ['/portfolio/index', 'slug' => $model->category->slug]];
}
$this->params['breadcrumbs'][] = $model->title;

$this->registerMetaTag(['name'=> 'keywords', 'content' => $model->metaKeywords]);
$this->registerMetaTag(['name'=> 'description', 'content' => $model->metaDescription]);

?>

<div class="content-header blog-column">
    <h1 class="page-title text-center"><?= $model->title?></h1>
</div>
<div class="content-page">
    <div class="content-column">
        <div class="content-body">
            <?= $model->desc?>
            <br>
            <?php if ($images = $model->images) { ?>
                <div class="row">
                    <?php foreach ($images as $item) { ?>
                        <div class="col-lg-6">
                            <a href="<?= $item->wmImage ?>" data-fancybox="images" data-caption="<?= $model->title ?>" class="portfolio-gallery__item mb-3 d-block">
                                <img src="<?= thumb($item->wmImagePath, 600, 400, true) ?>" alt="<?= $model->title ?>" class="hoverable" />
                            </a>
                        </div>
                    <?php } ?>
                </div>
            <?php } ?>
            <?php if ($relatedProducts) { ?>
                <h4 class="text-accent text-center mt-4 mb-4">
                    <?= t('Installed products') ?>
                </h4>
                <div class="product-list portfolio-product-list">
                    <?php foreach ($relatedProducts as $product) { ?>
                        <div class="pr-item-col">
                            <?= $this->render('/catalog/_item', [
                                'model' => $product
                            ]) ?>
                        </div>
                    <?php } ?>
                </div>
            <?php } ?>
        </div>
    </div>
</div>