common/models/Image.php
<?php

namespace common\models;

use common\models\helper\ImageHelper;
use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%image}}".
 *
 * @property integer $id
 * @property string $filename
 * @property integer $item_id
 * @property string $model_name
 * @property string $title
 * @property integer $sort_index
 * @property integer $folder
 */
class Image extends ActiveRecord
{

    public static function tableName()
    {
        return '{{%image}}';
    }

    public function rules()
    {
        return [
            [['filename', 'item_id', 'model_name'], 'required'],
            [['item_id', 'sort_index'], 'integer'],
            [['filename', 'model_name', 'title', 'folder'], 'string', 'max' => 255],
        ];
    }


    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'filename' => 'Filename',
            'folder' => 'Folder',
            'item_id' => 'Item ID',
            'model_name' => 'Model Name',
            'title' => 'Title',
            'sort_index' => 'Sort Index',
        ];
    }


    public function behaviors()
    {
        return [
            'sort' => [
                'class' => 'himiklab\sortablegrid\SortableGridBehavior',
                'sortableAttribute' => 'sort_index'
            ],
        ];

    }


    public function afterDelete()
    {
        parent::afterDelete(); //
        if ($this->checkFileExists()){
            unlink($this->filePath);
        }
    }

    public static function create($filename, $model_name, $item_id, $folder = false){
        $image = new self;
        $image->filename = $filename;
        $image->model_name = $model_name;
        $image->folder = $folder;
        $image->item_id = $item_id;
        $image->save();
    }


    public function getImage()
    {
        return ImageHelper::getImage($this->filename, $this->folder);
    }

    public function getWmImage()
    {
        return ImageHelper::getWmImage($this->filename, $this->folder);
    }

    public function getImagePath()
    {
        return ImageHelper::getImagePath($this->filename, $this->folder);
    }

    public function getWmImagePath()
    {
        return ImageHelper::getWmImagePath($this->filename, $this->folder);
    }


    public function getFileLink(){
        if ($this->checkFileExists()) {
            $file = ($this->folder) ? $this->folder.'/'.$this->filename : $this->filename;
            return Yii::getAlias('@imagesWebroot').'/' . $file;
        } else {
            return null;
        }
    }


    public function getFilePath(){
        if ($this->checkFileExists()) {
            $file = ($this->folder) ? $this->folder.'/'.$this->filename : $this->filename;
            return Yii::getAlias('@images').'/' . $file;
        } else {
            return null;
        }
    }


    public function checkFileExists(){
        if ($this->filename) {
            $file = ($this->folder) ? $this->folder.'/'.$this->filename : $this->filename;
            $filePath = Yii::getAlias('@images/') . ($file);
            if (file_exists($filePath)) {
                return true;
            } else {
                return false;
            }
        }
    }
}

frontend/models/Content.php
<?php

namespace frontend\models;

use common\modules\content\models\lang\ContentLang;

class Content extends \common\modules\content\models\Content
{

    public function getContent()
    {
        $content = ContentLang::find()->where(['content_id' => $this->id, 'lang_id' => Lang::getCurrent()->id])->one();
        if (!$content) {
            $content = ContentLang::find()->where(['content_id' => $this->id, 'lang_id' => Lang::getDefaultLang()->id])->one();
        }
        return $content;
    }

    public function getCategory()
    {
        return $this->hasOne(ContentCategory::className(), ['id' => 'category_id']);
    }

    public function getTitle()
    {
        return ($this->content) ? $this->content->title : '';
    }

    public function getDesc()
    {
        return ($this->content) ? $this->content->desc : '';
    }

    public function getIntro()
    {
        return ($this->content) ? $this->content->intro : '';
    }

    public function getMetaTitle()
    {
        return ($this->content) ? $this->content->meta_title : '';
    }

    public function getSeoTitle(){
        if ($this->content && $this->content->seo_title) {
            return $this->content->seo_title;
        }
        return ( $this->getTitle().' || '.siteName() );
    }

    public function getMetaKeywords()
    {
        return ($this->content) ? $this->content->meta_keywords : '';
    }

    public function getMetaDescription()
    {
        return ($this->content) ? $this->content->meta_description : '';
    }

    public function getSearchUrl(){
        switch ($this->section){
            case self::SECTION_PAGE :
                $url = ['/page/view', 'slug' => $this->slug];
                break;
            case self::SECTION_PORTFOLIOS :
                $url = ['/portfolio/view', 'slug' => $this->slug];
                break;
            case self::SECTION_NEWS :
                $url = ['/news/view', 'slug' => $this->slug];
                break;
            case self::SECTION_VACANCY :
                $url = ['/vacancy/view', 'slug' => $this->slug];
                break;
            default:
                $url = ['#'];
        }
        return $url;
    }
}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use common\modules\content\models\Content;
use common\modules\content\models\ContentCategory;
use common\modules\content\services\PortfolioWaterMarkService;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'cat'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionWm()
    {
        $models = Content::find()->andWhere(['section' => Content::SECTION_PORTFOLIOS])->all();
        foreach($models as $model){
            (new PortfolioWaterMarkService($model))->run();
        }
        return $this->request->referrer;
    }

    public function actionCat(){
        $models = Content::find()->andWhere(['section' => Content::SECTION_ARTICLE])->all();
        /** @var Content $model */
        foreach($models as $model){
            (new ContentCategory([
                'content_id' => $model->id,
                'category_id' => $model->category_id,
            ]))->save();
        }
        return $this->request->referrer;
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/views/site/_index_lids.php
<?php

use frontend\models\Feedback;
use himiklab\yii2\recaptcha\ReCaptcha2;
use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\widgets\MaskedInput;

$model = new Feedback();
$model->type_id = Feedback::LIDS;

?>

<div class="main-lids-form bg-light section-item">

    <div class="container">
        <div class="row f-aic">
            <div class="col-lg-3 offset-lg-2 text-center order-lg-1 order-2">
                <div class="main-lids__title">
                    <span>Получите Бесплатно</span>
                </div>
                <div class="main-lids__file">
                    <span>pdf-файл</span>
                </div>
                <div class="main-lids__catalog--name">
                    "Дизайн Код"
                </div>
                <div class="main-lids__catalog--desc">
                    <span>С помощью данной Методички</span>
                    <span>Вы узнаете правила правила архитектурной подсветки именно</span>
                    <span> для вашего сооружения.</span>
                </div>

                <div class="main-lids__form">
                    <?php $form = ActiveForm::begin(['id' => 'form-lids', 'action' => ['/site/feedback']]); ?>

                    <div>
                        <?=  $form->field($model, 'username')->hiddenInput(['value' => 'не задано', 'id' => 'lids-username'])->label(false); ?>
                        <?=  $form->field($model, 'email')->hiddenInput(['value' => 'не задано', 'id' => 'lids-email'])->label(false); ?>
                        <?= $form->field($model, 'type_id')->hiddenInput(['id' => 'lids-type_id'])->label(false); ?>
                        <?= $form->field($model, 'link')->hiddenInput(['value' => Yii::getAlias('@frontendWebroot').'/uploads/files/dizayn-kod-goroda.pdf', 'id' => 'lids-link'])->label(false); ?>

                        <?=  $form->field($model, 'phone')
                            ->widget(MaskedInput::className(), [
                                'mask'=> '+7 (999) 999-99-99',
                                'options' => [
                                    'id' => 'lids-phone',
                                ],
                            ])->label(t('You phone')); ?>


                            <?= $form->field($model, 'reCaptcha')->widget(
                                ReCaptcha2::class,
                                [
                                    'siteKey' => Feedback::RECAPTCHA_SITE_KEY,
                                    'id' => 'lids-reCaptcha',
                                ]
                            )->label(false) ?>

                        <div>
                            <?=  Html::submitButton('Скачать методичку', ['class' => 'btn btn-lg btn-outline-main w-100']); ?>
                        </div>

                    </div>

                    <?php  ActiveForm::end(); ?>
                </div>
            </div>
            <div class="col-lg-5 text-center order-lg-2 order-1">
                <img src="/img/lids-img.png" alt="">
            </div>
        </div>
    </div>
</div>

frontend/views/site/_main_image_bg.php
<?php
?>

<div class="main-image-wrap">
    <div class="overlay"></div>

    <div class="main-offer__wrap">
        <h1 class="main-offer"><?= txt('main_offer') ?></h1>
        <a data-fancybox data-src="#feedback-modal" href="javascript:;"
           class="btn btn-lg btn-main btn-rounded main-offer__link">
            <?= t('Send order') ?>
        </a>
    </div>
</div>

frontend/views/site/_main_special_bg.php
<?php
/** @var \frontend\models\Content[] $offers  */
?>

<div class="main-special-wrap">
    <div class="container">
        <div class="row">
            <div class="col-lg-7">
                <div id="main-slides">
                    <?php foreach ($offers as $offer) {?>
                        <div>
                            <h1 class="main-special-offer text-uppercase">
                                <?= $offer->getTitle() ?>
                            </h1>
                            <div class="main-special-list">
                                <?= $offer->getDesc() ?>
                            </div>
                            <br>
                            <div>
                                <a data-fancybox data-src="#free-callback-modal" href="javascript:;"
                                   class="btn btn-lg btn-main btn-rounded main-offer__link text-uppercase">
                                    <?= $offer->getIntro() ?>
                                </a>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
    <img src="/img/main-special-img.png" class="main-special__img d-none d-lg-block" alt="ledin.kz">
</div>

frontend/views/site/_main_video_bg.php
<?php
?>
<div class="main-video-wrap">
    <div class="overlay"></div>
    <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
        <source src="/uploads/files/dvorec_main.mp4" type="video/mp4">
    </video>

    <div class="main-offer__wrap">
        <h1 class="main-offer"><?= txt('main_offer') ?></h1>
        <a data-fancybox data-src="#feedback-modal" href="javascript:;"
           class="btn btn-lg btn-outline-main btn-rounded main-offer__link">
            <?= t('Send order') ?>
        </a>
    </div>
</div>

frontend/views/site/about.php
<?php
use common\models\Settings;

$this->title = t('About company').' | '.siteName();
$this->params['breadcrumbs'][] = t('About company');

$this->registerMetaTag(['name'=> 'keywords', 'content' => '']);
$this->registerMetaTag(['name'=> 'description', 'content' => 'На рынке с 2015 года. Основная деятельность нашей компании – это разработка проектов с нуля
и поставка оборудования для наружного и внутреннего освещения.']);

?>
<div class="company-page">
    <!-- Текст о компании -->
    <div class="company-page__main">
        <div class="container">
            <div class="company__text checked-list">
                <?= txt('company-text') ?>
            </div>
        </div>
    </div>

    <div class="team section-item">
        <div class="container">
            <h2 class="section-title text-accent text-uppercase">
                Команда
            </h2>
            <div class="row justify-content-center">
                <div class="col-lg-4 mb-1">
                    <a href="/img/team3.jpg" data-fancybox="images" data-caption="">
                        <img src="/img/team3-min.jpg" alt="" />
                    </a>
                </div>
                <div class="col-lg-4 mb-1">
                    <a href="/img/team1.jpg" data-fancybox="images" data-caption="">
                        <img src="/img/team1-min.jpg" alt="" />
                    </a>
                </div>
                <div class="col-lg-4 mb-1">
                    <a href="/img/team2.jpg" data-fancybox="images" data-caption="">
                        <img src="/img/team2-min.jpg" alt="" />
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="section-item">
        <div class="container adv">
            <div class="row">
                <div class="col-lg-2">
                    <img src="/img/adv-icon-1.png" alt="" class="adv__icon">
                </div>
                <div class="col-lg-10 checked-list adv-item">
                    <?= txt('about-adv-1') ?>
                </div>
            </div>
        </div>
    </div>

    <div class="section-item">
        <div class="container adv">
            <div class="row">
                <div class="col-lg-2">
                    <img src="/img/adv-icon-2.png" alt="" class="adv__icon">
                </div>
                <div class="col-lg-10 checked-list adv-item">
                    <?= txt('about-adv-2') ?>
                </div>
            </div>
        </div>
    </div>

    <div class="section-item">
        <div class="container adv">
            <div class="adv-item">
                <?= txt('about-adv-3') ?>
            </div>
        </div>
    </div>


    <!-- Карта -->
    <div class="container mb-4">
        <div class="map-desc__wrap">
            <div class="map-desc">
                <div class="map-title text-accent font-primary mb-2">
                    <?= txt('company-regions') ?>
                </div>
                <div class="map-objects">
                    <div class="map-objects__icon">
                        <img src="/svg/marker.svg" alt="">
                    </div>
                    <div class="map-objects__text">
                        <?= txt('company-objects-text')?>
                    </div>
                </div>
            </div>
        </div>
        <img src="/img/kzmap.jpg" alt="">
    </div>


    <!-- Нам доверяют -->
    <div class="container mb-4">
        <div class="about-awards">
            <h2 class="section-title text-accent text-center text-uppercase">
                Заслужили доверие и благодарность:
            </h2>
            <h6 class="awards-title text-center font-primary mb-4">
                <?= txt('about_award_title') ?>
            </h6>
            <div id="awards_images" class="d-flex">
                <a href="/img/sert.jpg" data-fancybox="images">
                    <img src="/img/sert-min.jpg" alt="">
                </a>
                <a href="/img/award1.jpg" data-fancybox="images">
                    <img src="/img/award1-min.jpg" alt="">
                </a>
                <a href="/img/award2.jpg" data-fancybox="images">
                    <img src="/img/award2-min.jpg" alt="">
                </a>
            </div>
            <div class="awards_text">
                <?= txt('about_award_text') ?>
            </div>
        </div>
    </div>

    <!-- Услугм -->
    <div class="container main-services-list">
        <div class="row">
            <?php if ($services) {
                foreach ($services as $service ) { ?>
                    <div class="col-lg-3 col-6">
                        <div class="main-service-item">
                            <div class="main-service-item__title"><?= $service->title ?></div>
                            <div class="main-service-item__img">
                                <img src="<?= thumb($service->imagePath, 600) ?>" alt="">
                            </div>
                            <div class="main-service-item__desc">
                                <?= $service->desc ?>
                            </div>
                        </div>
                    </div>
                <?php }
            } ?>
        </div>
    </div>

    <!-- Отзывы -->
    <?php if ($reviews) { ?>
        <section class="section-item">
            <div class="container">
                <h2 class="section-title text-accent text-center text-uppercase">
                    Отзывы клиентов
                </h2>
                <div class="reviews-list-wrap">
                    <div id="reviews-list">
                        <?php  foreach ($reviews as $review ) { ?>
                            <div>
                                <div class="review-item" style="background-image: url('<?= thumb($review->imagePath, 600) ?>')">
                                    <span>
                                        <a href="<?= $review->getIntro() ?>" data-fancybox>
                                            <img src="/svg/youtube.svg" alt="">
                                        </a>
                                    </span>
                                </div>
                            </div>
                        <?php } ?>

                    </div>
                </div>
            </div>
        </section>
    <?php } ?>

    <!-- Партнеры -->
    <?php if ($partners) { ?>
        <section class="section-item">
            <div class="container">
                <h2 class="section-title text-accent text-center text-uppercase">
                    Партнеры
                </h2>
                <div class="partners-list-wrap">
                    <div id="partners-list">
                        <?php  foreach ($partners as $partner ) { ?>
                            <div class="p-1">
                                <?= $this->render('/partners/_item', ['model' => $partner]) ?>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </section>
    <?php } ?>


    <div class="section-item">
        <div class="container adv">
            <div class="adv-item font-weight-bold">
                <?= txt('about-adv-4') ?>
            </div>
            <div class="text-center">
                <a data-fancybox data-src="#callback-modal" href="javascript:;" class="btn btn-lg btn-outline-main">
                    Оставить заявку
                </a>
            </div>
        </div>
    </div>

    <!-- FAQ -->
    <div class="container">
        <div class="faq-section__title font-primary text-accent">
            <?= t('FAQ') ?>
        </div>
        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <div class="faq-section__list">
                    <div class="accordion" id="accordionExample">
                        <?php if ($faqList) { $i = 0; foreach ($faqList as $item) { $i++; ?>
                            <div class="faq-item">
                                <h5>
                                    <a href="#" id="heading<?= $item->id ?>" class="faq-item__title collapsed shadow-sm d-block p-3"
                                       data-target="#collapse<?= $item->id ?>" aria-expanded="<?= $i==1 ? 'true' : 'false' ?>"
                                       data-toggle="collapse" aria-controls="collapse<?= $item->id ?>">
                                        <?= $item->title ?>
                                        <span class="float-right">
                                            <img src="/svg/down.svg" alt="" style="width: 15px;">
                                        </span>
                                    </a>
                                </h5>
                                <div id="collapse<?= $item->id ?>" class="collapse <?= $i==1 ? 'show' : '' ?> " aria-labelledby="heading<?= $item->id ?>" data-parent="#accordionExample">
                                    <div class="card-body faq-item__desc">
                                        <?= $item->desc ?>
                                    </div>
                                </div>
                            </div>
                        <?php } } ?>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>


<style>


</style>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="container">

    <h1 class="page-title font-primary"><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <br>
    <a href="<?= url(['/']) ?>" class="btn btn-sm btn-link"><?= t('Go to home') ?></a>


</div>

frontend/views/site/index.php
<?php

use common\models\Settings;

$this->title = siteName();
$this->registerMetaTag(['name' => 'description', 'content' => t('site_meta_desc')]);
?>


<?= $this->render('_main_special_bg', [
    'offers' => $offers
]) ?>


<?php if ($banners) { ?>
    <div id="main-banner-items" class="container-fluid">
        <div class="row">
            <?php foreach ($banners as $banner){ ?>
                <a href="<?= url($banner->link) ?>" class="col banner-item transitionable">
                <span class="banner-item__img">
                    <img src="<?= thumb($banner->imagePath, 800) ?>" alt="<?= $banner->title ?>">
                </span>
                    <span class="banner-item__title"><?= $banner->title ?></span>
                </a>
            <?php } ?>
        </div>
    </div>
<?php } ?>


<?php if ($projects) { ?>
    <section class="section-item pb-0">
         <h2 class="section-title text-center text-accent"><?= t('Our projects') ?></h2>
                <div id="main-project-items">
                <?php foreach ($projects as $project){ ?>
                    <div class="project-item" style="background-image: url('<?= thumb($project->imagePath, 600) ?>')">
                        <a href="<?= url(['/portfolio/view', 'slug' => $project->slug]) ?>" class="project-item__link">
                        <span class="project-item__title"><?= $project->title ?></span>
                    </a>
                </div>
            <?php } ?>
            <div class="project-item" style="background-image: url('/img/downlights.jpg')">
                <a href="<?= url(['/portfolio']) ?>" class="project-item__link">
                    <span class="project-item__title"><?= t('See all projects') ?></span>
                </a>
            </div>
        </div>
    </section>
<?php } ?>

<?= $this->render('_index_lids') ?>

<?php if ($news) { ?>
    <section class="section-item">
        <h2 class="section-title text-center text-accent"><?= t('Latest news') ?></h2>
        <div class="container">
            <div id="main-news-items">
                <?php foreach ($news as $item){ ?>
                    <div class="main-news-item">
                        <div class="news-item card hoverable h-100">
                            <a href="<?= url(['/news/view', 'slug' => $item->slug]) ?>" class="d-block">
                                <img src="<?= thumb($item->imagePath, 400, 400) ?>" alt="<?= $item->title ?>">
                                <span class="d-block card-body">
                                    <small class="d-block text-accent mb-1">
                                        <?= Yii::$app->formatter->asDate($item->created_at) ?>
                                    </small>
                                    <span class="d-block">
                                        <?= $item->title ?>
                                    </span>
                                </span>
                            </a>
                        </div>
                    </div>
                <?php } ?>
            </div>
        </div>
    </section>
<?php } ?>

frontend/views/site/offline.php
<?php
?>

<h1>Ведутся технические работы </h1>



frontend/views/site/search.php
<?php

use yii\widgets\ListView;
use yii\helpers\Url;

$this->title = siteName();
$this->params['breadcrumbs'][] = 'Поиск товаров';

?>

<div class="container">

    <div class="row">
        <div class="col-lg-12">

            <h1><?= t('Site search') ?></h1>

            <form action="<?= Url::toRoute(['/site/search']) ?>" method="get">
                <div class="h-search-box">
                    <input name="key" class="form-control h-search-input" type="text" placeholder="Поиск"
                           value="<?= $key ?>">
                    <button class="h-search-btn">
                        <img src="/svg/search.svg" alt="">
                    </button>
                </div>
            </form>

            <br>
            <ul class="nav nav-tabs" id="searchTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="product-tab" data-toggle="tab" href="#product" role="tab" aria-controls="product" aria-selected="true">
                        <?= t('Products') ?>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="category-tab" data-toggle="tab" href="#category" role="tab" aria-controls="category" aria-selected="false">
                        <?= t('Categories') ?>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="page-tab" data-toggle="tab" href="#page" role="tab" aria-controls="page" aria-selected="false">
                        <?= t('Information') ?>
                    </a>
                </li>
            </ul>
            <div class="tab-content pt-3" id="searchTabContent">
                <div class="tab-pane fade show active" id="product" role="tabpanel" aria-labelledby="product-tab">
                    <?php if ($dataProvider) {
                        echo ListView::widget([
                            'dataProvider' => $dataProvider,
                            'itemView' => '/catalog/_item',
                            'options' => [
                                'tag' => 'div',
                                'class' => 'product-list'
                            ],
                            'itemOptions' => [
                                'tag' => 'div',
                                'class' => 'pr-item-col search-pr-item-col',
                            ],
                            'pager' => [
                                'maxButtonCount' => 3,
                            ],
                            'layout' => "{items}\n<div class='clearfix'></div>{pager}",
                        ]) ;
                    } ?>
                </div>
                <div class="tab-pane fade" id="category" role="tabpanel" aria-labelledby="category-tab">
                    <?php if ($categories){ ?>
                        <?php foreach ($categories as $category) { ?>
                            <a href="<?= url(['/catalog', 'slug' => $category->slug]) ?>" class="dashed d-inline-block mb-3"><?= $category->title ?></a><br>
                        <?php } ?>
                    <?php } else { ?>
                        <span><?= t('No results found.', 'yii') ?></span>
                    <?php } ?>
                </div>
                <div class="tab-pane fade" id="page" role="tabpanel" aria-labelledby="page-tab">
                    <?php if ($pages){ ?>
                        <?php foreach ($pages as $key => $model) { ?>
                            <h6 class="mt-4">
                                <strong><?= t($key) ?></strong>
                            </h6>
                            <a href="<?= url($model->searchUrl) ?>" class="dashed"><?= $model->title ?></a>
                        <?php } ?>
                    <?php } else { ?>
                        <span><?= t('No results found.', 'yii') ?></span>
                    <?php } ?>
                </div>
            </div>

        </div>
    </div>

</div>




